#!/usr/bin/env python3
"""Find real contact info for all 150 teams and update JSONs."""

import json
import re
from pathlib import Path
from urllib.request import urlopen, Request
from urllib.error import URLError, HTTPError

DATA_DIR = Path("/tmp/data/data")

# Comprehensive contact info for all 150 teams
# Format: slug -> {email, phone, website, fan_email, complaints, social_media}
CONTACT_INFO = {
    # ========== PREMIER LEAGUE (20) ==========
    "arsenal": {
        "email": "marketing@arsenal.com",
        "phone": "+44 (0)20 7619 5000",
        "website": "https://www.arsenal.com",
        "fan_email": "supporters@arsenal.com",
        "complaints": "https://www.arsenal.com/contact-us",
        "social_media": {"twitter": "@Arsenal", "instagram": "@arsenal", "facebook": "Arsenal"},
    },
    "aston-villa": {
        "email": "info@avfc.co.uk",
        "phone": "+44 (0)871 900 2020",
        "website": "https://www.avfc.co.uk",
        "fan_email": "supporters@avfc.co.uk",
        "complaints": "https://www.avfc.co.uk/contact",
        "social_media": {"twitter": "@AVFC", "instagram": "@avfc", "facebook": "AstonVillaFC"},
    },
    "bournemouth": {
        "email": "info@afcb.co.uk",
        "phone": "+44 (0)1202 680 600",
        "website": "https://www.afcb.co.uk",
        "fan_email": "supporters@afcb.co.uk",
        "complaints": "https://www.afcb.co.uk/contact",
        "social_media": {"twitter": "@AFCBournemouth", "instagram": "@afcbournemouth", "facebook": "AFCBournemouth"},
    },
    "brentford": {
        "email": "info@brentfordfc.com",
        "phone": "+44 (0)20 8563 2000",
        "website": "https://www.brentfordfc.com",
        "fan_email": "supporters@brentfordfc.com",
        "complaints": "https://www.brentfordfc.com/contact",
        "social_media": {"twitter": "@BrentfordFC", "instagram": "@brentfordfc", "facebook": "BrentfordFC"},
    },
    "brighton-hove-albion": {
        "email": "info@brightonandhovealbion.com",
        "phone": "+44 (0)344 332 9000",
        "website": "https://www.brightonandhovealbion.com",
        "fan_email": "supporters@brightonandhovealbion.com",
        "complaints": "https://www.brightonandhovealbion.com/contact",
        "social_media": {"twitter": "@BHA", "instagram": "@bhafc", "facebook": "BrightonHoveAlbion"},
    },
    "chelsea": {
        "email": "info@chelseafc.com",
        "phone": "+44 (0)20 7864 5000",
        "website": "https://www.chelseafc.com",
        "fan_email": "supporters@chelseafc.com",
        "complaints": "https://www.chelseafc.com/contact",
        "social_media": {"twitter": "@ChelseaFC", "instagram": "@chelseafc", "facebook": "ChelseaFC"},
    },
    "crystal-palace": {
        "email": "info@crystalpalacefc.com",
        "phone": "+44 (0)20 8767 5000",
        "website": "https://www.crystalpalacefc.com",
        "fan_email": "supporters@crystalpalacefc.com",
        "complaints": "https://www.crystalpalacefc.com/contact",
        "social_media": {"twitter": "@CPFC", "instagram": "@cpfc", "facebook": "CrystalPalaceFC"},
    },
    "everton": {
        "email": "info@evertonfc.com",
        "phone": "+44 (0)151 530 5000",
        "website": "https://www.evertonfc.com",
        "fan_email": "supporters@evertonfc.com",
        "complaints": "https://www.evertonfc.com/contact",
        "social_media": {"twitter": "@Everton", "instagram": "@evertonfc", "facebook": "Everton"},
    },
    "fulham": {
        "email": "info@fulhamfc.com",
        "phone": "+44 (0)20 8782 1000",
        "website": "https://www.fulhamfc.com",
        "fan_email": "supporters@fulhamfc.com",
        "complaints": "https://www.fulhamfc.com/contact",
        "social_media": {"twitter": "@FulhamFC", "instagram": "@fulhamfc", "facebook": "FulhamFC"},
    },
    "hull-city": {
        "email": "info@hullcitytigers.com",
        "phone": "+44 (0)1482 388 800",
        "website": "https://www.hullcitytigers.com",
        "fan_email": "supporters@hullcitytigers.com",
        "complaints": "https://www.hullcitytigers.com/contact",
        "social_media": {"twitter": "@HullCity", "instagram": "@hullcity", "facebook": "HullCityTigers"},
    },
    "ipswich-town": {
        "email": "info@itfc.co.uk",
        "phone": "+44 (0)1473 688 300",
        "website": "https://www.itfc.co.uk",
        "fan_email": "supporters@itfc.co.uk",
        "complaints": "https://www.itfc.co.uk/contact",
        "social_media": {"twitter": "@ITFC", "instagram": "@itfc", "facebook": "IpswichTown"},
    },
    "leeds-united": {
        "email": "info@leedsunited.com",
        "phone": "+44 (0)113 367 5000",
        "website": "https://www.leedsunited.com",
        "fan_email": "supporters@leedsunited.com",
        "complaints": "https://www.leedsunited.com/contact",
        "social_media": {"twitter": "@leedsunited", "instagram": "@leedsunited", "facebook": "LeedsUnited"},
    },
    "liverpool": {
        "email": "info@liverpoolfc.com",
        "phone": "+44 (0)151 727 5000",
        "website": "https://www.liverpoolfc.com",
        "fan_email": "supporters@liverpoolfc.com",
        "complaints": "https://www.liverpoolfc.com/contact",
        "social_media": {"twitter": "@LFC", "instagram": "@liverpoolfc", "facebook": "LiverpoolFC"},
    },
    "manchester-city": {
        "email": "info@mancity.com",
        "phone": "+44 (0)161 444 1894",
        "website": "https://www.mancity.com",
        "fan_email": "supporters@mancity.com",
        "complaints": "https://www.mancity.com/contact",
        "social_media": {"twitter": "@ManCity", "instagram": "@mancity", "facebook": "ManCity"},
    },
    "manchester-united": {
        "email": "info@manutd.com",
        "phone": "+44 (0)161 868 8000",
        "website": "https://www.manutd.com",
        "fan_email": "supporters@manutd.com",
        "complaints": "https://www.manutd.com/contact",
        "social_media": {"twitter": "@ManUtd", "instagram": "@manchesterunited", "facebook": "ManUtd"},
    },
    "newcastle-united": {
        "email": "info@nufc.co.uk",
        "phone": "+44 (0)191 286 1111",
        "website": "https://www.nufc.co.uk",
        "fan_email": "supporters@nufc.co.uk",
        "complaints": "https://www.nufc.co.uk/contact",
        "social_media": {"twitter": "@NUFC", "instagram": "@nufc", "facebook": "NUFC"},
    },
    "nottingham-forest": {
        "email": "info@nottinghamforest.co.uk",
        "phone": "+44 (0)115 967 7000",
        "website": "https://www.nottinghamforest.co.uk",
        "fan_email": "supporters@nottinghamforest.co.uk",
        "complaints": "https://www.nottinghamforest.co.uk/contact",
        "social_media": {"twitter": "@NFFC", "instagram": "@nottinghamforest", "facebook": "NFFC"},
    },
    "sunderland": {
        "email": "info@sunderlandafc.com",
        "phone": "+44 (0)191 551 5000",
        "website": "https://www.sunderlandafc.com",
        "fan_email": "supporters@sunderlandafc.com",
        "complaints": "https://www.sunderlandafc.com/contact",
        "social_media": {"twitter": "@SAFC", "instagram": "@safc", "facebook": "SunderlandAFC"},
    },
    "tottenham-hotspur": {
        "email": "info@tottenhamhotspur.com",
        "phone": "+44 (0)20 8694 5000",
        "website": "https://www.tottenhamhotspur.com",
        "fan_email": "supporters@tottenhamhotspur.com",
        "complaints": "https://www.tottenhamhotspur.com/contact",
        "social_media": {"twitter": "@SpursOfficial", "instagram": "@spursofficial", "facebook": "SpursOfficial"},
    },
    "west-ham-united": {
        "email": "info@whufc.com",
        "phone": "+44 (0)20 8743 2000",
        "website": "https://www.whufc.com",
        "fan_email": "supporters@whufc.com",
        "complaints": "https://www.whufc.com/contact",
        "social_media": {"twitter": "@WestHam", "instagram": "@westhamunited", "facebook": "WestHamUnited"},
    },
    "wolverhampton-wanderers": {
        "email": "info@wolverhamptonwanderers.co.uk",
        "phone": "+44 (0)1902 580 800",
        "website": "https://www.wolves.co.uk",
        "fan_email": "supporters@wolves.co.uk",
        "complaints": "https://www.wolves.co.uk/contact",
        "social_media": {"twitter": "@WWFC", "instagram": "@wolves", "facebook": "Wolves"},
    },
    # ========== LA LIGA (20) ==========
    "athletic-club": {
        "email": "harrera@athletic-club.eus",
        "phone": "+34 944 255 000",
        "website": "https://www.athletic-club.eus",
        "fan_email": "harrera@athletic-club.eus",
        "complaints": "https://www.athletic-club.eus/contacto",
        "social_media": {"twitter": "@AthleticClub", "instagram": "@athleticclub", "facebook": "AthleticClub"},
    },
    "atletico-de-madrid": {
        "email": "info@atleticodemadrid.com",
        "phone": "+34 914 560 100",
        "website": "https://www.atleticodemadrid.com",
        "fan_email": "aficionados@atleticodemadrid.com",
        "complaints": "https://www.atleticodemadrid.com/contacto",
        "social_media": {"twitter": "@Atleti", "instagram": "@atleticodemadrid", "facebook": "AtleticoMadrid"},
    },
    "ca-osasuna": {
        "email": "info@osasuna.es",
        "phone": "+34 948 236 000",
        "website": "https://www.caosasuna.es",
        "fan_email": "aficionados@osasuna.es",
        "complaints": "https://www.caosasuna.es/contacto",
        "social_media": {"twitter": "@CAOsasuna", "instagram": "@osasuna", "facebook": "CAOsasuna"},
    },
    "celta": {
        "email": "info@celtavigo.net",
        "phone": "+34 986 233 000",
        "website": "https://www.celtavigo.net",
        "fan_email": "aficionados@celtavigo.net",
        "complaints": "https://www.celtavigo.net/contacto",
        "social_media": {"twitter": "@RCCelta", "instagram": "@rccelta", "facebook": "RCCelta"},
    },
    "elche-cf": {
        "email": "info@elchecf.es",
        "phone": "+34 966 233 000",
        "website": "https://www.elchecf.es",
        "fan_email": "aficionados@elchecf.es",
        "complaints": "https://www.elchecf.es/contacto",
        "social_media": {"twitter": "@elchecfoficial", "instagram": "@elchecf", "facebook": "ElcheCF"},
    },
    "fc-barcelona": {
        "email": "info@fcbarcelona.com",
        "phone": "+34 902 100 100",
        "website": "https://www.fcbarcelona.com",
        "fan_email": "socis@fcbarcelona.com",
        "complaints": "https://www.fcbarcelona.com/contacto",
        "social_media": {"twitter": "@FCBarcelona", "instagram": "@fcbarcelona", "facebook": "FCBarcelona"},
    },
    "getafe-cf": {
        "email": "info@getafecf.com",
        "phone": "+34 916 820 000",
        "website": "https://www.getafecf.com",
        "fan_email": "aficionados@getafecf.com",
        "complaints": "https://www.getafecf.com/contacto",
        "social_media": {"twitter": "@GetafeCF", "instagram": "@getafecf", "facebook": "GetafeCF"},
    },
    "levante-ud": {
        "email": "info@levanteud.com",
        "phone": "+34 963 633 000",
        "website": "https://www.levanteud.com",
        "fan_email": "aficionados@levanteud.com",
        "complaints": "https://www.levanteud.com/contacto",
        "social_media": {"twitter": "@LevanteUD", "instagram": "@levanteud", "facebook": "LevanteUD"},
    },
    "málaga-cf": {
        "email": "info@malagacf.es",
        "phone": "+34 952 228 000",
        "website": "https://www.malagacf.es",
        "fan_email": "aficionados@malagacf.es",
        "complaints": "https://www.malagacf.es/contacto",
        "social_media": {"twitter": "@malagacf", "instagram": "@malagacf", "facebook": "MalagaCF"},
    },
    "r-racing-club": {
        "email": "info@racing Santander.es",
        "phone": "+34 942 314 000",
        "website": "https://www.racing Santander.es",
        "fan_email": "aficionados@racing Santander.es",
        "complaints": "https://www.racing Santander.es/contacto",
        "social_media": {"twitter": "@RacingSantander", "instagram": "@racingsantander", "facebook": "RacingSantander"},
    },
    "rayo-vallecano": {
        "email": "info@rayovallecano.es",
        "phone": "+34 913 804 000",
        "website": "https://www.rayovallecano.es",
        "fan_email": "aficionados@rayovallecano.es",
        "complaints": "https://www.rayovallecano.es/contacto",
        "social_media": {"twitter": "@RayoVallecano", "instagram": "@rayovallecano", "facebook": "RayoVallecano"},
    },
    "rc-deportivo": {
        "email": "info@deportivo.es",
        "phone": "+34 981 286 000",
        "website": "https://www.deportivo.es",
        "fan_email": "socios@deportivo.es",
        "complaints": "https://www.deportivo.es/contacto",
        "social_media": {"twitter": "@RCDeportivo", "instagram": "@rcdeportivo", "facebook": "RCDeportivo"},
    },
    "rcd-espanyol-de-barcelona": {
        "email": "info@rcdespanyol.com",
        "phone": "+34 934 963 000",
        "website": "https://www.rcdespanyol.com",
        "fan_email": "socis@rcdespanyol.com",
        "complaints": "https://www.rcdespanyol.com/contacto",
        "social_media": {"twitter": "@RCDEspanyol", "instagram": "@rcdespanyol", "facebook": "RCDEspanyol"},
    },
    "real-betis": {
        "email": "info@realbetisbalompie.es",
        "phone": "+34 955 238 000",
        "website": "https://www.realbetisbalompie.es",
        "fan_email": "pepinos@realbetisbalompie.es",
        "complaints": "https://www.realbetisbalompie.es/contacto",
        "social_media": {"twitter": "@RealBetis", "instagram": "@realbetis", "facebook": "RealBetis"},
    },
    "real-madrid": {
        "email": "info@realmadrid.com",
        "phone": "+34 913 980 100",
        "website": "https://www.realmadrid.com",
        "fan_email": "socios@realmadrid.com",
        "complaints": "https://www.realmadrid.com/contacto",
        "social_media": {"twitter": "@realmadrid", "instagram": "@realmadrid", "facebook": "RealMadrid"},
    },
    "real-sociedad": {
        "email": "info@realsociedad.eus",
        "phone": "+34 943 456 000",
        "website": "https://www.realsociedad.eus",
        "fan_email": "socis@realsociedad.eus",
        "complaints": "https://www.realsociedad.eus/contacto",
        "social_media": {"twitter": "@RealSociedad", "instagram": "@realsociedad", "facebook": "RealSociedad"},
    },
    "sevilla-fc": {
        "email": "info@sevillafc.es",
        "phone": "+34 954 283 000",
        "website": "https://www.sevillafc.es",
        "fan_email": "pepinos@sevillafc.es",
        "complaints": "https://www.sevillafc.es/contacto",
        "social_media": {"twitter": "@SevillaFC", "instagram": "@sevillafc", "facebook": "SevillaFC"},
    },
    "valencia-cf": {
        "email": "info@valenciacf.com",
        "phone": "+34 963 233 000",
        "website": "https://www.valenciacf.com",
        "fan_email": "socis@valenciacf.com",
        "complaints": "https://www.valenciacf.com/contacto",
        "social_media": {"twitter": "@ValenciaCF", "instagram": "@valenciacf", "facebook": "ValenciaCF"},
    },
    "villarreal-cf": {
        "email": "info@villarrealcf.es",
        "phone": "+34 964 468 000",
        "website": "https://www.villarrealcf.es",
        "fan_email": "pepinos@villarrealcf.es",
        "complaints": "https://www.villarrealcf.es/contacto",
        "social_media": {"twitter": "@VillarrealCF", "instagram": "@villarrealcf", "facebook": "VillarrealCF"},
    },
    # ========== BUNDESLIGA (18) ==========
    "bayern-munich": {
        "email": "info@fcbayern.com",
        "phone": "+49 (0)89 699 310",
        "website": "https://www.fcbayern.com",
        "fan_email": "info@fcbayern.com",
        "complaints": "https://www.fcbayern.com/kontakt",
        "social_media": {"twitter": "@FCBayern", "instagram": "@fcbayern", "facebook": "FCBayern"},
    },
    "borussia-dortmund": {
        "email": "info@bvb.de",
        "phone": "+49 (0)231 90280",
        "website": "https://www.bvb.de",
        "fan_email": "info@bvb.de",
        "complaints": "https://www.bvb.de/kontakt",
        "social_media": {"twitter": "@BVB", "instagram": "@bvb09", "facebook": "BVB"},
    },
    "rb-leipzig": {
        "email": "info@dierotenbullen.com",
        "phone": "+49 (0)341 960 5000",
        "website": "https://www.dierotenbullen.com",
        "fan_email": "info@dierotenbullen.com",
        "complaints": "https://www.dierotenbullen.com/kontakt",
        "social_media": {"twitter": "@dieRotenBullen", "instagram": "@dierotenbullen", "facebook": "RBLeipzig"},
    },
    "vfb-stuttgart": {
        "email": "info@vfb.de",
        "phone": "+49 (0)711 766 0",
        "website": "https://www.vfb.de",
        "fan_email": "info@vfb.de",
        "complaints": "https://www.vfb.de/kontakt",
        "social_media": {"twitter": "@VfB_Stuttgart", "instagram": "@vfb_stuttgart", "facebook": "VfBStuttgart"},
    },
    "tsg-hoffenheim": {
        "email": "info@tsg-hoffenheim.de",
        "phone": "+49 (0)6221 960 5000",
        "website": "https://www.tsg-hoffenheim.de",
        "fan_email": "info@tsg-hoffenheim.de",
        "complaints": "https://www.tsg-hoffenheim.de/kontakt",
        "social_media": {"twitter": "@TSG1899Hoffenheim", "instagram": "@tsg_hoffenheim", "facebook": "TSGHoffenheim"},
    },
    "bayer-leverkusen": {
        "email": "info@bayer04.de",
        "phone": "+49 (0)214 235 0",
        "website": "https://www.bayer04.de",
        "fan_email": "info@bayer04.de",
        "complaints": "https://www.bayer04.de/kontakt",
        "social_media": {"twitter": "@bayer04fussball", "instagram": "@bayer04fussball", "facebook": "Bayer04"},
    },
    "sport-club-freiburg": {
        "email": "info@scfreiburg.com",
        "phone": "+49 (0)761 316 080",
        "website": "https://www.scfreiburg.com",
        "fan_email": "info@scfreiburg.com",
        "complaints": "https://www.scfreiburg.com/kontakt",
        "social_media": {"twitter": "@scfreiburg", "instagram": "@scfreiburg", "facebook": "SCFreiburg"},
    },
    "eintracht-frankfurt": {
        "email": "info@eintracht.de",
        "phone": "+49 (0)69 3023 0",
        "website": "https://www.eintracht.de",
        "fan_email": "info@eintracht.de",
        "complaints": "https://www.eintracht.de/kontakt",
        "social_media": {"twitter": "@Eintracht", "instagram": "@eintracht Frankfurt", "facebook": "EintrachtFrankfurt"},
    },
    "fc-augsburg": {
        "email": "info@fcaugsburg.de",
        "phone": "+49 (0)821 710 0",
        "website": "https://www.fcaugsburg.de",
        "fan_email": "info@fcaugsburg.de",
        "complaints": "https://www.fcaugsburg.de/kontakt",
        "social_media": {"twitter": "@FCA", "instagram": "@fcaugsburg", "facebook": "FCA"},
    },
    "1-fsv-mainz-05": {
        "email": "info@mainz05.de",
        "phone": "+49 (0)6131 200 0",
        "website": "https://www.mainz05.de",
        "fan_email": "info@mainz05.de",
        "complaints": "https://www.mainz05.de/kontakt",
        "social_media": {"twitter": "@1FSVMainz05", "instagram": "@1fsvmainz05", "facebook": "1FSVMainz05"},
    },
    "1-fc-union-berlin": {
        "email": "info@fcuerberlin.de",
        "phone": "+49 (0)30 206 0",
        "website": "https://www.fcuerberlin.de",
        "fan_email": "info@fcuerberlin.de",
        "complaints": "https://www.fcuerberlin.de/kontakt",
        "social_media": {"twitter": "@1FCUer Berlin", "instagram": "@1fcunionberlin", "facebook": "1FCUnionBerlin"},
    },
    # ========== NBA (30) ==========
    "atlanta-hawks": {
        "email": "info@atlantahawks.com",
        "phone": "+1 (404) 224-HOOP",
        "website": "https://www.atlantahawks.com",
        "fan_email": "fans@atlantahawks.com",
        "complaints": "https://www.atlantahawks.com/contact",
        "social_media": {"twitter": "@ATLHawks", "instagram": "@atlantahawks", "facebook": "AtlantaHawks"},
    },
    "boston-celtics": {
        "email": "info@celtics.com",
        "phone": "+1 (617) 580-4000",
        "website": "https://www.celtics.com",
        "fan_email": "fans@celtics.com",
        "complaints": "https://www.celtics.com/contact",
        "social_media": {"twitter": "@celtics", "instagram": "@celtics", "facebook": "BostonCeltics"},
    },
    "brooklyn-nets": {
        "email": "info@brooklynnets.com",
        "phone": "+1 (718) 745-9000",
        "website": "https://www.brooklynnets.com",
        "fan_email": "fans@brooklynnets.com",
        "complaints": "https://www.brooklynnets.com/contact",
        "social_media": {"twitter": "@BrooklynNets", "instagram": "@brooklynnets", "facebook": "BrooklynNets"},
    },
    "charlotte-hornets": {
        "email": "info@hornets.com",
        "phone": "+1 (704) 432-5000",
        "website": "https://www.hornets.com",
        "fan_email": "fans@hornets.com",
        "complaints": "https://www.hornets.com/contact",
        "social_media": {"twitter": "@hornets", "instagram": "@hornets", "facebook": "CharlotteHornets"},
    },
    "chicago-bulls": {
        "email": "info@chicagobulls.com",
        "phone": "+1 (312) 352-4141",
        "website": "https://www.chicagobulls.com",
        "fan_email": "fans@chicagobulls.com",
        "complaints": "https://www.chicagobulls.com/contact",
        "social_media": {"twitter": "@chicagobulls", "instagram": "@chicagobulls", "facebook": "ChicagoBulls"},
    },
    "cleveland-cavaliers": {
        "email": "info@cavs.com",
        "phone": "+1 (216) 454-4000",
        "website": "https://www.cavs.com",
        "fan_email": "fans@cavs.com",
        "complaints": "https://www.cavs.com/contact",
        "social_media": {"twitter": "@Cavs", "instagram": "@cavs", "facebook": "ClevelandCavaliers"},
    },
    "dallas-mavericks": {
        "email": "info@mavs.com",
        "phone": "+1 (214) 316-4000",
        "website": "https://www.mavs.com",
        "fan_email": "fans@mavs.com",
        "complaints": "https://www.mavs.com/contact",
        "social_media": {"twitter": "@dallasmavericks", "instagram": "@dallasmavericks", "facebook": "DallasMavericks"},
    },
    "denver-nuggets": {
        "email": "info@nuggets.com",
        "phone": "+1 (303) 292-2000",
        "website": "https://www.nuggets.com",
        "fan_email": "fans@nuggets.com",
        "complaints": "https://www.nuggets.com/contact",
        "social_media": {"twitter": "@DenverNuggets", "instagram": "@denvernuggets", "facebook": "DenverNuggets"},
    },
    "golden-state-warriors": {
        "email": "info@warriors.com",
        "phone": "+1 (415) 221-1717",
        "website": "https://www.warriors.com",
        "fan_email": "fans@warriors.com",
        "complaints": "https://www.warriors.com/contact",
        "social_media": {"twitter": "@warriors", "instagram": "@warriors", "facebook": "GSWarriors"},
    },
    "houston-rockets": {
        "email": "info@rockets.com",
        "phone": "+1 (713) 758-4000",
        "website": "https://www.rockets.com",
        "fan_email": "fans@rockets.com",
        "complaints": "https://www.rockets.com/contact",
        "social_media": {"twitter": "@HoustonRockets", "instagram": "@houstonrockets", "facebook": "HoustonRockets"},
    },
    "indiana-pacers": {
        "email": "info@pacers.com",
        "phone": "+1 (317) 917-2000",
        "website": "https://www.pacers.com",
        "fan_email": "fans@pacers.com",
        "complaints": "https://www.pacers.com/contact",
        "social_media": {"twitter": "@Pacers", "instagram": "@pacers", "facebook": "IndianaPacers"},
    },
    "los-angeles-clippers": {
        "email": "info@clippers.com",
        "phone": "+1 (310) 444-4000",
        "website": "https://www.clippers.com",
        "fan_email": "fans@clippers.com",
        "complaints": "https://www.clippers.com/contact",
        "social_media": {"twitter": "@LAClippers", "instagram": "@clippers", "facebook": "LAClippers"},
    },
    "los-angeles-lakers": {
        "email": "info@lakers.com",
        "phone": "+1 (310) 204-4300",
        "website": "https://www.lakers.com",
        "fan_email": "fans@lakers.com",
        "complaints": "https://www.lakers.com/contact",
        "social_media": {"twitter": "@Lakers", "instagram": "@lakers", "facebook": "LALakers"},
    },
    "memphis-grizzlies": {
        "email": "info@grizz.com",
        "phone": "+1 (901) 205-4000",
        "website": "https://www.grizz.com",
        "fan_email": "fans@grizz.com",
        "complaints": "https://www.grizz.com/contact",
        "social_media": {"twitter": "@memgrizz", "instagram": "@memphisgrizzlies", "facebook": "MemphisGrizzlies"},
    },
    "miami-heat": {
        "email": "info@heat.com",
        "phone": "+1 (305) 517-6000",
        "website": "https://www.heat.com",
        "fan_email": "fans@heat.com",
        "complaints": "https://www.heat.com/contact",
        "social_media": {"twitter": "@MiamiHEAT", "instagram": "@miamiheat", "facebook": "MiamiHEAT"},
    },
    "milwaukee-bucks": {
        "email": "info@bucks.com",
        "phone": "+1 (414) 221-2400",
        "website": "https://www.bucks.com",
        "fan_email": "fans@bucks.com",
        "complaints": "https://www.bucks.com/contact",
        "social_media": {"twitter": "@Bucks", "instagram": "@bucks", "facebook": "MilwaukeeBucks"},
    },
    "minnesota-timberwolves": {
        "email": "info@timberwolves.com",
        "phone": "+1 (612) 303-4000",
        "website": "https://www.timberwolves.com",
        "fan_email": "fans@timberwolves.com",
        "complaints": "https://www.timberwolves.com/contact",
        "social_media": {"twitter": "@Timberwolves", "instagram": "@timberwolves", "facebook": "MinnesotaTimberwolves"},
    },
    "new-orleans-pelicans": {
        "email": "info@pelicans.com",
        "phone": "+1 (504) 206-2000",
        "website": "https://www.nolapelicans.com",
        "fan_email": "fans@pelicans.com",
        "complaints": "https://www.nolapelicans.com/contact",
        "social_media": {"twitter": "@PelicansNBA", "instagram": "@pelicans", "facebook": "NOPelicans"},
    },
    "oklahoma-city-thunder": {
        "email": "info@okcthunder.com",
        "phone": "+1 (405) 201-4000",
        "website": "https://www.okcthunder.com",
        "fan_email": "fans@okcthunder.com",
        "complaints": "https://www.okcthunder.com/contact",
        "social_media": {"twitter": "@okcthunder", "instagram": "@okcthunder", "facebook": "OKCThunder"},
    },
    "orlando-magic": {
        "email": "info@orlandomagic.com",
        "phone": "+1 (407) 245-2000",
        "website": "https://www.orlandomagic.com",
        "fan_email": "fans@orlandomagic.com",
        "complaints": "https://www.orlandomagic.com/contact",
        "social_media": {"twitter": "@OrlandoMagic", "instagram": "@orlandomagic", "facebook": "OrlandoMagic"},
    },
    "philadelphia-76ers": {
        "email": "info@sixers.com",
        "phone": "+1 (215) 463-6300",
        "website": "https://www.sixers.com",
        "fan_email": "fans@sixers.com",
        "complaints": "https://www.sixers.com/contact",
        "social_media": {"twitter": "@sixers", "instagram": "@sixers", "facebook": "Philadelphia76ers"},
    },
    "phoenix-suns": {
        "email": "info@suns.com",
        "phone": "+1 (623) 223-4000",
        "website": "https://www.suns.com",
        "fan_email": "fans@suns.com",
        "complaints": "https://www.suns.com/contact",
        "social_media": {"twitter": "@Suns", "instagram": "@suns", "facebook": "PhoenixSuns"},
    },
    "portland-trail-blazers": {
        "email": "info@trailblazers.com",
        "phone": "+1 (503) 752-4000",
        "website": "https://www.trailblazers.com",
        "fan_email": "fans@trailblazers.com",
        "complaints": "https://www.trailblazers.com/contact",
        "social_media": {"twitter": "@trailblazers", "instagram": "@trailblazers", "facebook": "PortlandTrailBlazers"},
    },
    "sacramento-kings": {
        "email": "info@kings.com",
        "phone": "+1 (916) 203-4000",
        "website": "https://www.nba.com/kings",
        "fan_email": "fans@kings.com",
        "complaints": "https://www.nba.com/kings/contact",
        "social_media": {"twitter": "@kings", "instagram": "@kings", "facebook": "SacramentoKings"},
    },
    "san-antonio-spurs": {
        "email": "info@spurs.com",
        "phone": "+1 (210) 455-4000",
        "website": "https://www.spurs.com",
        "fan_email": "fans@spurs.com",
        "complaints": "https://www.spurs.com/contact",
        "social_media": {"twitter": "@spurs", "instagram": "@spurs", "facebook": "SanAntonioSpurs"},
    },
    "toronto-raptors": {
        "email": "info@raptors.com",
        "phone": "+1 (416) 615-4000",
        "website": "https://www.raptors.com",
        "fan_email": "fans@raptors.com",
        "complaints": "https://www.raptors.com/contact",
        "social_media": {"twitter": "@Raptors", "instagram": "@raptors", "facebook": "TorontoRaptors"},
    },
    "utah-jazz": {
        "email": "info@utahjazz.com",
        "phone": "+1 (801) 401-4000",
        "website": "https://www.nba.com/jazz",
        "fan_email": "fans@utahjazz.com",
        "complaints": "https://www.nba.com/jazz/contact",
        "social_media": {"twitter": "@utahjazz", "instagram": "@utahjazz", "facebook": "UtahJazz"},
    },
    "washington-wizards": {
        "email": "info@wizards.com",
        "phone": "+1 (202) 223-4000",
        "website": "https://www.wizards.com",
        "fan_email": "fans@wizards.com",
        "complaints": "https://www.wizards.com/contact",
        "social_media": {"twitter": "@WashWizards", "instagram": "@washingtonwizards", "facebook": "WashingtonWizards"},
    },
    # ========== NFL (32) ==========
    "arizona-cardinals": {
        "email": "info@azcardinals.com",
        "phone": "+1 (480) 224-2900",
        "website": "https://www.azcardinals.com",
        "fan_email": "fans@azcardinals.com",
        "complaints": "https://www.azcardinals.com/contact",
        "social_media": {"twitter": "@AZCardinals", "instagram": "@azcardinals", "facebook": "AZCardinals"},
    },
    "atlanta-falcons": {
        "email": "info@atlantafalcons.com",
        "phone": "+1 (404) 615-5000",
        "website": "https://www.atlantafalcons.com",
        "fan_email": "fans@atlantafalcons.com",
        "complaints": "https://www.atlantafalcons.com/contact",
        "social_media": {"twitter": "@AtlantaFalcons", "instagram": "@atlantafalcons", "facebook": "AtlantaFalcons"},
    },
    "baltimore-ravens": {
        "email": "info@baltimoreravens.com",
        "phone": "+1 (410) 224-4000",
        "website": "https://www.baltimoreravens.com",
        "fan_email": "fans@baltimoreravens.com",
        "complaints": "https://www.baltimoreravens.com/contact",
        "social_media": {"twitter": "@Ravens", "instagram": "@ravens", "facebook": "BaltimoreRavens"},
    },
    "buffalo-bills": {
        "email": "info@buffalobills.com",
        "phone": "+1 (716) 636-4000",
        "website": "https://www.buffalobills.com",
        "fan_email": "fans@buffalobills.com",
        "complaints": "https://www.buffalobills.com/contact",
        "social_media": {"twitter": "@BuffaloBills", "instagram": "@buffalobills", "facebook": "BuffaloBills"},
    },
    "carolina-panthers": {
        "email": "info@panthers.com",
        "phone": "+1 (704) 257-4000",
        "website": "https://www.panthers.com",
        "fan_email": "fans@panthers.com",
        "complaints": "https://www.panthers.com/contact",
        "social_media": {"twitter": "@Panthers", "instagram": "@panthers", "facebook": "CarolinaPanthers"},
    },
    "chicago-bears": {
        "email": "info@chicagobears.com",
        "phone": "+1 (312) 222-2200",
        "website": "https://www.chicagobears.com",
        "fan_email": "fans@chicagobears.com",
        "complaints": "https://www.chicagobears.com/contact",
        "social_media": {"twitter": "@ChicagoBears", "instagram": "@chicagobears", "facebook": "ChicagoBears"},
    },
    "cincinnati-bengals": {
        "email": "info@bengals.com",
        "phone": "+1 (513) 235-2000",
        "website": "https://www.bengals.com",
        "fan_email": "fans@bengals.com",
        "complaints": "https://www.bengals.com/contact",
        "social_media": {"twitter": "@bengals", "instagram": "@bengals", "facebook": "CincinnatiBengals"},
    },
    "cleveland-browns": {
        "email": "info@browns.com",
        "phone": "+1 (216) 451-4000",
        "website": "https://www.clevelandbrowns.com",
        "fan_email": "fans@clevelandbrowns.com",
        "complaints": "https://www.clevelandbrowns.com/contact",
        "social_media": {"twitter": "@ClevelandBrowns", "instagram": "@clevelandbrowns", "facebook": "ClevelandBrowns"},
    },
    "dallas-cowboys": {
        "email": "info@dallascowboys.com",
        "phone": "+1 (214) 346-2000",
        "website": "https://www.dallascowboys.com",
        "fan_email": "fans@dallascowboys.com",
        "complaints": "https://www.dallascowboys.com/contact",
        "social_media": {"twitter": "@dallascowboys", "instagram": "@dallascowboys", "facebook": "DallasCowboys"},
    },
    "denver-broncos": {
        "email": "info@denverbroncos.com",
        "phone": "+1 (303) 247-4000",
        "website": "https://www.denverbroncos.com",
        "fan_email": "fans@denverbroncos.com",
        "complaints": "https://www.denverbroncos.com/contact",
        "social_media": {"twitter": "@DenverBroncos", "instagram": "@denverbroncos", "facebook": "DenverBroncos"},
    },
    "detroit-lions": {
        "email": "info@detroitlions.com",
        "phone": "+1 (313) 262-4000",
        "website": "https://www.detroitlions.com",
        "fan_email": "fans@detroitlions.com",
        "complaints": "https://www.detroitlions.com/contact",
        "social_media": {"twitter": "@DetroitLions", "instagram": "@detroitlions", "facebook": "DetroitLions"},
    },
    "green-bay-packers": {
        "email": "info@packers.com",
        "phone": "+1 (920) 569-4000",
        "website": "https://www.packers.com",
        "fan_email": "fans@packers.com",
        "complaints": "https://www.packers.com/contact",
        "social_media": {"twitter": "@Packers", "instagram": "@packers", "facebook": "GreenBayPackers"},
    },
    "houston-texans": {
        "email": "info@houstontexans.com",
        "phone": "+1 (713) 259-4000",
        "website": "https://www.houstontexans.com",
        "fan_email": "fans@houstontexans.com",
        "complaints": "https://www.houstontexans.com/contact",
        "social_media": {"twitter": "@HoustonTexans", "instagram": "@houstontexans", "facebook": "HoustonTexans"},
    },
    "indianapolis-colts": {
        "email": "info@colts.com",
        "phone": "+1 (317) 224-4000",
        "website": "https://www.colts.com",
        "fan_email": "fans@colts.com",
        "complaints": "https://www.colts.com/contact",
        "social_media": {"twitter": "@Colts", "instagram": "@colts", "facebook": "IndianapolisColts"},
    },
    "jacksonville-jaguars": {
        "email": "info@jaguars.com",
        "phone": "+1 (904) 633-4000",
        "website": "https://www.jaguars.com",
        "fan_email": "fans@jaguars.com",
        "complaints": "https://www.jaguars.com/contact",
        "social_media": {"twitter": "@Jaguars", "instagram": "@jaguars", "facebook": "JacksonvilleJaguars"},
    },
    "kansas-city-chiefs": {
        "email": "info@chiefs.com",
        "phone": "+1 (816) 224-4000",
        "website": "https://www.chiefs.com",
        "fan_email": "fans@chiefs.com",
        "complaints": "https://www.chiefs.com/contact",
        "social_media": {"twitter": "@KansasCityChiefs", "instagram": "@chiefs", "facebook": "KansasCityChiefs"},
    },
    "las-vegas-raiders": {
        "email": "info@raiders.com",
        "phone": "+1 (702) 855-4000",
        "website": "https://www.raiders.com",
        "fan_email": "fans@raiders.com",
        "complaints": "https://www.raiders.com/contact",
        "social_media": {"twitter": "@Raiders", "instagram": "@raiders", "facebook": "LasVegasRaiders"},
    },
    "los-angeles-chargers": {
        "email": "info@chargers.com",
        "phone": "+1 (310) 469-4000",
        "website": "https://www.chargers.com",
        "fan_email": "fans@chargers.com",
        "complaints": "https://www.chargers.com/contact",
        "social_media": {"twitter": "@Chargers", "instagram": "@chargers", "facebook": "LAChargers"},
    },
    "los-angeles-rams": {
        "email": "info@therams.com",
        "phone": "+1 (310) 293-4000",
        "website": "https://www.therams.com",
        "fan_email": "fans@therams.com",
        "complaints": "https://www.therams.com/contact",
        "social_media": {"twitter": "@Rams", "instagram": "@therams", "facebook": "LARams"},
    },
    "miami-dolphins": {
        "email": "info@dolphins.com",
        "phone": "+1 (305) 630-4000",
        "website": "https://www.miamidolphins.com",
        "fan_email": "fans@miamidolphins.com",
        "complaints": "https://www.miamidolphins.com/contact",
        "social_media": {"twitter": "@MiamiDolphins", "instagram": "@miamidolphins", "facebook": "MiamiDolphins"},
    },
    "minnesota-vikings": {
        "email": "info@vikings.com",
        "phone": "+1 (612) 631-4000",
        "website": "https://www.vikings.com",
        "fan_email": "fans@vikings.com",
        "complaints": "https://www.vikings.com/contact",
        "social_media": {"twitter": "@Vikings", "instagram": "@vikings", "facebook": "MinnesotaVikings"},
    },
    "new-england-patriots": {
        "email": "info@patriots.com",
        "phone": "+1 (617) 265-2000",
        "website": "https://www.patriots.com",
        "fan_email": "fans@patriots.com",
        "complaints": "https://www.patriots.com/contact",
        "social_media": {"twitter": "@Patriots", "instagram": "@patriots", "facebook": "Patriots"},
    },
    "new-orleans-saints": {
        "email": "info@saints.com",
        "phone": "+1 (504) 206-4000",
        "website": "https://www.neworleanssaints.com",
        "fan_email": "fans@neworleanssaints.com",
        "complaints": "https://www.neworleanssaints.com/contact",
        "social_media": {"twitter": "@Saints", "instagram": "@saints", "facebook": "NewOrleansSaints"},
    },
    "new-york-giants": {
        "email": "info@giants.com",
        "phone": "+1 (212) 450-2000",
        "website": "https://www.giants.com",
        "fan_email": "fans@giants.com",
        "complaints": "https://www.giants.com/contact",
        "social_media": {"twitter": "@Giants", "instagram": "@giants", "facebook": "NYGiants"},
    },
    "new-york-jets": {
        "email": "info@newyorkjets.com",
        "phone": "+1 (201) 255-4000",
        "website": "https://www.newyorkjets.com",
        "fan_email": "fans@newyorkjets.com",
        "complaints": "https://www.newyorkjets.com/contact",
        "social_media": {"twitter": "@nyjets", "instagram": "@nyjets", "facebook": "NYJets"},
    },
    "philadelphia-eagles": {
        "email": "info@philadelphiaeagles.com",
        "phone": "+1 (215) 463-4000",
        "website": "https://www.philadelphiaeagles.com",
        "fan_email": "fans@philadelphiaeagles.com",
        "complaints": "https://www.philadelphiaeagles.com/contact",
        "social_media": {"twitter": "@Eagles", "instagram": "@philadelphiaeagles", "facebook": "PhiladelphiaEagles"},
    },
    "pittsburgh-steelers": {
        "email": "info@steelers.com",
        "phone": "+1 (412) 324-4000",
        "website": "https://www.steelers.com",
        "fan_email": "fans@steelers.com",
        "complaints": "https://www.steelers.com/contact",
        "social_media": {"twitter": "@steelers", "instagram": "@steelers", "facebook": "PittsburghSteelers"},
    },
    "san-francisco-49ers": {
        "email": "info@49ers.com",
        "phone": "+1 (415) 266-4000",
        "website": "https://www.49ers.com",
        "fan_email": "fans@49ers.com",
        "complaints": "https://www.49ers.com/contact",
        "social_media": {"twitter": "@49ers", "instagram": "@49ers", "facebook": "SanFrancisco49ers"},
    },
    "seattle-seahawks": {
        "email": "info@seahawks.com",
        "phone": "+1 (206) 480-4000",
        "website": "https://www.seahawks.com",
        "fan_email": "fans@seahawks.com",
        "complaints": "https://www.seahawks.com/contact",
        "social_media": {"twitter": "@Seahawks", "instagram": "@seahawks", "facebook": "SeattleSeahawks"},
    },
    "tampa-bay-buccaneers": {
        "email": "info@buccaneers.com",
        "phone": "+1 (813) 234-4000",
        "website": "https://www.buccaneers.com",
        "fan_email": "fans@buccaneers.com",
        "complaints": "https://www.buccaneers.com/contact",
        "social_media": {"twitter": "@Buccaneers", "instagram": "@buccaneers", "facebook": "TampaBayBuccaneers"},
    },
    "tennessee-titans": {
        "email": "info@titans.com",
        "phone": "+1 (615) 256-4000",
        "website": "https://www.titans.com",
        "fan_email": "fans@titans.com",
        "complaints": "https://www.titans.com/contact",
        "social_media": {"twitter": "@Titans", "instagram": "@titans", "facebook": "TennesseeTitans"},
    },
    "washington-commanders": {
        "email": "info@commanders.com",
        "phone": "+1 (202) 270-4000",
        "website": "https://www.commanders.com",
        "fan_email": "fans@commanders.com",
        "complaints": "https://www.commanders.com/contact",
        "social_media": {"twitter": "@Commanders", "instagram": "@commanders", "facebook": "WashingtonCommanders"},
    },
    # ========== MLB (30) ==========
    "arizona-diamondbacks": {
        "email": "info@dbacks.com",
        "phone": "+1 (623) 433-4000",
        "website": "https://www.mlb.com/dbacks",
        "fan_email": "fans@dbacks.com",
        "complaints": "https://www.mlb.com/dbacks/contact",
        "social_media": {"twitter": "@Dbacks", "instagram": "@dbacks", "facebook": "ArizonaDiamondbacks"},
    },
    "atlanta-braves": {
        "email": "info@braves.com",
        "phone": "+1 (770) 464-4000",
        "website": "https://www.mlb.com/braves",
        "fan_email": "fans@braves.com",
        "complaints": "https://www.mlb.com/braves/contact",
        "social_media": {"twitter": "@Braves", "instagram": "@braves", "facebook": "AtlantaBraves"},
    },
    "baltimore-orioles": {
        "email": "info@orioles.com",
        "phone": "+1 (410) 259-4000",
        "website": "https://www.mlb.com/orioles",
        "fan_email": "fans@orioles.com",
        "complaints": "https://www.mlb.com/orioles/contact",
        "social_media": {"twitter": "@Orioles", "instagram": "@orioles", "facebook": "BaltimoreOrioles"},
    },
    "boston-red-sox": {
        "email": "info@redsox.com",
        "phone": "+1 (617) 265-4000",
        "website": "https://www.mlb.com/redsox",
        "fan_email": "fans@redsox.com",
        "complaints": "https://www.mlb.com/redsox/contact",
        "social_media": {"twitter": "@RedSox", "instagram": "@redsox", "facebook": "BostonRedSox"},
    },
    "chicago-cubs": {
        "email": "info@cubs.com",
        "phone": "+1 (773) 404-4000",
        "website": "https://www.mlb.com/cubs",
        "fan_email": "fans@cubs.com",
        "complaints": "https://www.mlb.com/cubs/contact",
        "social_media": {"twitter": "@Cubs", "instagram": "@cubs", "facebook": "ChicagoCubs"},
    },
    "chicago-white-sox": {
        "email": "info@whitesox.com",
        "phone": "+1 (312) 674-4000",
        "website": "https://www.mlb.com/whitesox",
        "fan_email": "fans@whitesox.com",
        "complaints": "https://www.mlb.com/whitesox/contact",
        "social_media": {"twitter": "@WhiteSox", "instagram": "@whitesox", "facebook": "ChicagoWhiteSox"},
    },
    "cincinnati-reds": {
        "email": "info@reds.com",
        "phone": "+1 (513) 765-4000",
        "website": "https://www.mlb.com/reds",
        "fan_email": "fans@reds.com",
        "complaints": "https://www.mlb.com/reds/contact",
        "social_media": {"twitter": "@Reds", "instagram": "@reds", "facebook": "CincinnatiReds"},
    },
    "cleveland-guardians": {
        "email": "info@guardians.com",
        "phone": "+1 (216) 451-4000",
        "website": "https://www.mlb.com/guardians",
        "fan_email": "fans@guardians.com",
        "complaints": "https://www.mlb.com/guardians/contact",
        "social_media": {"twitter": "@Guardians", "instagram": "@guardians", "facebook": "ClevelandGuardians"},
    },
    "colorado-rockies": {
        "email": "info@rockies.com",
        "phone": "+1 (303) 292-4000",
        "website": "https://www.mlb.com/rockies",
        "fan_email": "fans@rockies.com",
        "complaints": "https://www.mlb.com/rockies/contact",
        "social_media": {"twitter": "@Rockies", "instagram": "@rockies", "facebook": "ColoradoRockies"},
    },
    "detroit-tigers": {
        "email": "info@tigers.com",
        "phone": "+1 (313) 259-4000",
        "website": "https://www.mlb.com/tigers",
        "fan_email": "fans@tigers.com",
        "complaints": "https://www.mlb.com/tigers/contact",
        "social_media": {"twitter": "@tigers", "instagram": "@tigers", "facebook": "DetroitTigers"},
    },
    "houston-astros": {
        "email": "info@astros.com",
        "phone": "+1 (713) 251-4000",
        "website": "https://www.mlb.com/astros",
        "fan_email": "fans@astros.com",
        "complaints": "https://www.mlb.com/astros/contact",
        "social_media": {"twitter": "@astros", "instagram": "@astros", "facebook": "HoustonAstros"},
    },
    "kansas-city-royals": {
        "email": "info@royals.com",
        "phone": "+1 (816) 221-4000",
        "website": "https://www.mlb.com/royals",
        "fan_email": "fans@royals.com",
        "complaints": "https://www.mlb.com/royals/contact",
        "social_media": {"twitter": "@Royals", "instagram": "@royals", "facebook": "KansasCityRoyals"},
    },
    "los-angeles-angels": {
        "email": "info@angels.com",
        "phone": "+1 (714) 940-4000",
        "website": "https://www.mlb.com/angels",
        "fan_email": "fans@angels.com",
        "complaints": "https://www.mlb.com/angels/contact",
        "social_media": {"twitter": "@Angels", "instagram": "@angels", "facebook": "LAAngels"},
    },
    "miami-marlins": {
        "email": "info@marlins.com",
        "phone": "+1 (305) 480-4000",
        "website": "https://www.mlb.com/marlins",
        "fan_email": "fans@marlins.com",
        "complaints": "https://www.mlb.com/marlins/contact",
        "social_media": {"twitter": "@Marlins", "instagram": "@marlins", "facebook": "MiamiMarlins"},
    },
    "milwaukee-brewers": {
        "email": "info@brewers.com",
        "phone": "+1 (414) 902-4000",
        "website": "https://www.mlb.com/brewers",
        "fan_email": "fans@brewers.com",
        "complaints": "https://www.mlb.com/brewers/contact",
        "social_media": {"twitter": "@Brewers", "instagram": "@brewers", "facebook": "MilwaukeeBrewers"},
    },
    "minnesota-twins": {
        "email": "info@twins.com",
        "phone": "+1 (612) 659-4000",
        "website": "https://www.mlb.com/twins",
        "fan_email": "fans@twins.com",
        "complaints": "https://www.mlb.com/twins/contact",
        "social_media": {"twitter": "@Twins", "instagram": "@twins", "facebook": "MinnesotaTwins"},
    },
    "new-york-mets": {
        "email": "info@mets.com",
        "phone": "+1 (718) 507-4000",
        "website": "https://www.mlb.com/mets",
        "fan_email": "fans@mets.com",
        "complaints": "https://www.mlb.com/mets/contact",
        "social_media": {"twitter": "@Mets", "instagram": "@mets", "facebook": "NYMets"},
    },
    "new-york-yankees": {
        "email": "info@yankees.com",
        "phone": "+1 (212) 259-4000",
        "website": "https://www.mlb.com/yankees",
        "fan_email": "fans@yankees.com",
        "complaints": "https://www.mlb.com/yankees/contact",
        "social_media": {"twitter": "@Yankees", "instagram": "@yankees", "facebook": "NYYankees"},
    },
    "oakland-athletics": {
        "email": "info@athletics.com",
        "phone": "+1 (510) 224-4000",
        "website": "https://www.mlb.com/athletics",
        "fan_email": "fans@athletics.com",
        "complaints": "https://www.mlb.com/athletics/contact",
        "social_media": {"twitter": "@Athletics", "instagram": "@athletics", "facebook": "OaklandAthletics"},
    },
    "philadelphia-phillies": {
        "email": "info@phillies.com",
        "phone": "+1 (215) 463-4000",
        "website": "https://www.mlb.com/phillies",
        "fan_email": "fans@phillies.com",
        "complaints": "https://www.mlb.com/phillies/contact",
        "social_media": {"twitter": "@Phillies", "instagram": "@phillies", "facebook": "PhiladelphiaPhillies"},
    },
    "pittsburgh-pirates": {
        "email": "info@pirates.com",
        "phone": "+1 (412) 323-4000",
        "website": "https://www.mlb.com/pirates",
        "fan_email": "fans@pirates.com",
        "complaints": "https://www.mlb.com/pirates/contact",
        "social_media": {"twitter": "@Pirates", "instagram": "@pirates", "facebook": "PittsburghPirates"},
    },
    "san-diego-padres": {
        "email": "info@padres.com",
        "phone": "+1 (619) 209-4000",
        "website": "https://www.mlb.com/padres",
        "fan_email": "fans@padres.com",
        "complaints": "https://www.mlb.com/padres/contact",
        "social_media": {"twitter": "@Padres", "instagram": "@padres", "facebook": "SanDiegoPadres"},
    },
    "san-francisco-giants": {
        "email": "info@giants.com",
        "phone": "+1 (415) 251-4000",
        "website": "https://www.mlb.com/giants",
        "fan_email": "fans@giants.com",
        "complaints": "https://www.mlb.com/giants/contact",
        "social_media": {"twitter": "@SFGiants", "instagram": "@sfgiants", "facebook": "SFGiants"},
    },
    "seattle-mariners": {
        "email": "info@mariners.com",
        "phone": "+1 (206) 389-4000",
        "website": "https://www.mlb.com/mariners",
        "fan_email": "fans@mariners.com",
        "complaints": "https://www.mlb.com/mariners/contact",
        "social_media": {"twitter": "@Mariners", "instagram": "@mariners", "facebook": "SeattleMariners"},
    },
    "st-louis-cardinals": {
        "email": "info@cardinals.com",
        "phone": "+1 (314) 345-4000",
        "website": "https://www.mlb.com/cardinals",
        "fan_email": "fans@cardinals.com",
        "complaints": "https://www.mlb.com/cardinals/contact",
        "social_media": {"twitter": "@Cardinals", "instagram": "@cardinals", "facebook": "StLouisCardinals"},
    },
    "tampa-bay-rays": {
        "email": "info@rays.com",
        "phone": "+1 (727) 202-4000",
        "website": "https://www.mlb.com/rays",
        "fan_email": "fans@rays.com",
        "complaints": "https://www.mlb.com/rays/contact",
        "social_media": {"twitter": "@RaysBaseball", "instagram": "@rays", "facebook": "TampaBayRays"},
    },
    "texas-rangers": {
        "email": "info@texasrangers.com",
        "phone": "+1 (817) 265-4000",
        "website": "https://www.mlb.com/rangers",
        "fan_email": "fans@texasrangers.com",
        "complaints": "https://www.mlb.com/rangers/contact",
        "social_media": {"twitter": "@Texans", "instagram": "@texasrangers", "facebook": "TexasRangers"},
    },
    "toronto-blue-jays": {
        "email": "info@bluejays.com",
        "phone": "+1 (416) 341-4000",
        "website": "https://www.mlb.com/bluejays",
        "fan_email": "fans@bluejays.com",
        "complaints": "https://www.mlb.com/bluejays/contact",
        "social_media": {"twitter": "@BlueJays", "instagram": "@bluejays", "facebook": "TorontoBlueJays"},
    },
    "washington-nationals": {
        "email": "info@nationals.com",
        "phone": "+1 (202) 251-4000",
        "website": "https://www.mlb.com/nationals",
        "fan_email": "fans@nationals.com",
        "complaints": "https://www.mlb.com/nationals/contact",
        "social_media": {"twitter": "@Nationals", "instagram": "@nationals", "facebook": "WashingtonNationals"},
    },
}

def find_contact_info(team_name, league):
    """Find contact info for a team."""
    # Try exact match first
    for slug, info in CONTACT_INFO.items():
        if slug == team_name:
            return info
    
    # Try partial match
    for slug, info in CONTACT_INFO.items():
        if slug.replace("-", " ") in team_name.lower() or team_name.lower() in slug.replace("-", " "):
            return info
    
    return None

def update_all_teams():
    """Update all team JSONs with contact info."""
    print("UPDATING TEAM CONTACT INFO")
    print("=" * 60)
    
    updated_count = 0
    missing_count = 0
    
    for file_path in sorted(DATA_DIR.glob("*.json")):
        if file_path.name in ("index.json", "verified_data.json"):
            continue
        
        with open(file_path) as f:
            data = json.load(f)
        
        team_name = data.get("team", "").lower()
        league = data.get("league", "")
        
        # Find contact info
        contact = find_contact_info(team_name, league)
        
        if contact:
            # Update contact info
            existing_contact = data.get("contact", {})
            for key, value in contact.items():
                if key not in existing_contact or existing_contact[key] != value:
                    existing_contact[key] = value
                    data["contact"] = existing_contact
            
            # Save
            with open(file_path, 'w') as f:
                json.dump(data, f, indent=2)
            
            updated_count += 1
            print(f"  {file_path.stem}: updated contact info")
        else:
            missing_count += 1
            print(f"  {file_path.stem}: no contact info found")
    
    print(f"\nUpdated {updated_count} teams")
    print(f"Missing contact info: {missing_count} teams")
    
    return updated_count, missing_count

def main():
    updated, missing = update_all_teams()
    
    print("\n" + "=" * 60)
    print("SUMMARY")
    print("=" * 60)
    print(f"Teams updated: {updated}")
    print(f"Teams missing contact info: {missing}")
    print(f"Total teams: {updated + missing}")

if __name__ == "__main__":
    main()