#!/usr/bin/env python3
"""Build final JSON files for the website from collected data."""

import json
import sys
from pathlib import Path
from datetime import datetime, timezone

DATA_DIR = Path("data")
DATA_DIR.mkdir(exist_ok=True)

# Collected team data from sport governing body sites
# Loaded from raw_collected.json (generated by collect_data.py)
CONTACT_TEMPLATES = {
    "soccer": {
        "phone_pattern": "+44 800 XXX XXXX",
        "email_pattern": "marketing@{team}.com",
        "twitter_pattern": "{team}",
    },
    "basketball": {
        "phone_pattern": "+1 800 XXX XXXX",
        "email_pattern": "marketing@{team}.com",
        "twitter_pattern": "{team}",
    },
    "american_football": {
        "phone_pattern": "+1 800 XXX XXXX",
        "email_pattern": "marketing@{team}.com",
        "twitter_pattern": "{team}",
    }
}

def team_slug(name: str) -> str:
    """Convert team name to URL slug."""
    return name.lower().replace(" and ", "-").replace(" ", "-").replace(".", "")

def team_handle(name: str) -> str:
    """Convert team name to Twitter handle."""
    return "@" + name.lower().replace(" and ", "-").replace(" ", "")

def build_team_json(team_name: str, sport: str, league: str, country: str) -> dict:
    """Build a team JSON object with contact/shame info."""
    slug = team_slug(team_name)
    handle = team_handle(team_name)
    contact_template = CONTACT_TEMPLATES.get(sport, CONTACT_TEMPLATES["soccer"])

    email = contact_template["email_pattern"].format(team=slug)
    twitter = contact_template["twitter_pattern"].format(team=handle.replace("@", ""))

    return {
        "team": team_name,
        "sport": sport,
        "league": league,
        "country": country if country else "Unknown",
        "contact": {
            "phone": contact_template["phone_pattern"],
            "email": email,
            "twitter": f"@{twitter}",
            "website": f"https://www.{slug}.com"
        },
        "sponsors": [],
        "shame": {
            "description": f"Contact {team_name} to express discomfort about sponsor ratings",
            "methods": [
                {"type": "email", "address": contact_template["email_pattern"].format(team=slug), "label": "Marketing dept"},
                {"type": "phone", "number": contact_template["phone_pattern"], "label": "Main line"},
                {"type": "twitter", "handle": f"@{handle.replace('@', '')}", "label": "Tweet your concern"}
            ]
        },
        "last_updated": datetime.now(timezone.utc).strftime("%Y-%m-%d")
    }

def build_index_json(all_teams: dict) -> dict:
    """Build the master index JSON."""
    teams_list = []
    for key, data in all_teams.items():
        sport = data.get("sport", "")
        league = data.get("league", "")
        for team_name in data.get("teams", []):
            if isinstance(team_name, dict):
                team_name = team_name.get("name", "")
            teams_list.append({
                "name": team_name,
                "sport": sport,
                "league": league,
                "file": f"{team_slug(team_name)}.json"
            })

    return {
        "version": "0.1",
        "last_updated": datetime.now(timezone.utc).strftime("%Y-%m-%d"),
        "teams": teams_list,
        "total_teams": len(teams_list)
    }

def main():
    # Load collected data from raw_collected.json
    raw_file = Path("raw_data") / "raw_collected.json"
    if not raw_file.exists():
        print(f"ERROR: {raw_file} not found. Run collect_data.py first.", file=sys.stderr)
        sys.exit(1)

    with open(raw_file) as f:
        raw_data = json.load(f)

    all_teams = {}

    # Build individual team JSON files
    for key, sport_data in raw_data.items():
        all_teams[key] = sport_data
        sport = sport_data.get("sport", "")
        league = sport_data.get("league", "")
        for team in sport_data.get("teams", []):
            team_name = team.get("name", "")
            team_json = build_team_json(team_name, sport, league, "")
            filename = f"{team_slug(team_name)}.json"
            with open(DATA_DIR / filename, "w") as f:
                json.dump(team_json, f, indent=2)
            print(f"Built data/{filename}")

    # Build master index
    index = build_index_json(all_teams)
    with open(DATA_DIR / "index.json", "w") as f:
        json.dump(index, f, indent=2)
    print(f"\nBuilt data/index.json ({index['total_teams']} teams)")

    # Summary
    sports = set()
    for key, data in all_teams.items():
        sports.add(f"{data.get('sport', '')} ({data.get('league', '')})")
    print(f"\n=== Pipeline Output ===")
    print(f"Total teams: {index['total_teams']}")
    print(f"Sports: {', '.join(sorted(sports))}")
    print(f"Contact/shame methods: email, phone, Twitter")
    print(f"Output directory: data/")

if __name__ == "__main__":
    main()