#!/usr/bin/env python3
"""Build final JSON files for the website from collected data + Wikipedia sponsor info."""

import json
import re
import sys
from pathlib import Path
from datetime import datetime, timezone
from urllib.request import urlopen, Request
from urllib.error import URLError, HTTPError

DATA_DIR = Path("data")
DATA_DIR.mkdir(exist_ok=True)
OUTPUT_DIR = Path("raw_data")
OUTPUT_DIR.mkdir(exist_ok=True)

# Collected team data from sport governing body sites
# Loaded from raw_collected.json (generated by collect_data.py)
CONTACT_TEMPLATES = {
    "soccer": {
        "phone_pattern": "+44 800 XXX XXXX",
        "email_pattern": "marketing@{team}.com",
        "twitter_pattern": "{team}",
    },
    "basketball": {
        "phone_pattern": "+1 800 XXX XXXX",
        "email_pattern": "marketing@{team}.com",
        "twitter_pattern": "{team}",
    },
    "american_football": {
        "phone_pattern": "+1 800 XXX XXXX",
        "email_pattern": "marketing@{team}.com",
        "twitter_pattern": "{team}",
    }
}

# Wikipedia page names for each team slug
TEAM_WIKIPEDIA = {
    # Premier League
    "arsenal": "Arsenal_F.C.",
    "aston-villa": "Aston_Villa_F.C.",
    "bournemouth": "AFC_Bournemouth",
    "brentford": "Brentford_F.C.",
    "chelsea": "Chelsea_F.C.",
    "everton": "Everton_F.C.",
    "liverpool": "Liverpool_F.C.",
    "manchester-city": "Manchester_City_F.C.",
    "manchester-united": "Manchester_United_F.C.",
    "newcastle-united": "Newcastle_United_F.C.",
    "nottingham-forest": "Nottingham_Forest_F.C.",
    "sunderland": "Sunderland_A.F.C.",
    "tottenham-hotspur": "Tottenham_Hotspur_F.C.",
    # La Liga
    "athletic-club": "Athletic_Bilbao",
    "atletico-de-madrid": "Atlético_Madrid",
    "ca-osasuna": "CA_Osasuna",
    "celta": "RC_Celta_de_Vigo",
    "elche-cf": "Elche_CF",
    "fc-barcelona": "FC_Barcelona",
    "getafe-cf": "Getafe_CF",
    "levante-ud": "Levante_UD",
    "málaga-cf": "Málaga_CF",
    "r-racing-club": "Racing_de_Santander",
    "rayo-vallecano": "Rayo_Vallecano",
    "rc-deportivo": "Deportivo_de_La_Coruña",
    "rcd-espanyol-de-barcelona": "RCD_Espanyol",
    "real-betis": "Real_Betis",
    "real-madrid": "Real_Madrid_CF",
    "real-sociedad": "Real_Sociedad",
    "sevilla-fc": "Sevilla_FC",
    "valencia-cf": "Valencia_CF",
    "villarreal-cf": "Villarreal_CF",
    # Bundesliga
    "bayern-munich": "FC_Bayern_Munich",
    "borussia-dortmund": "Borussia_Dortmund",
    "rb-leipzig": "RB_Leipzig",
    "vfb-stuttgart": "VfB_Stuttgart",
    "tsg-hoffenheim": "TSG_1899_Hoffenheim",
    "bayer-leverkusen": "Bayer_04_Leverkusen",
    "sport-club-freiburg": "SC_Freiburg",
    "eintracht-frankfurt": "Eintracht_Frankfurt",
    "fc-augsburg": "FC_Augsburg",
    "1-fsv-mainz-05": "1._FSV_Mainz_05",
    "1-fc-union-berlin": "1._FC_Union_Berlin",
    "borussia-mönchengladbach": "Borussia_Mönchengladbach",
    "hamburger-sv": "Hamburger_SV",
    "1-fc-köln": "1._FC_Köln",
    "sv-werder-bremen": "SV_Werder_Bremen",
    "fc-schalke-04": "FC_Schalke_04",
    "sv-elversberg": "SV_Elversberg",
    "sc-paderborn-07": "SC_Paderborn_07",
    "deportivo-alaves": "Deportivo_Alavés",
    # NBA
    "atlanta-hawks": "Atlanta_Hawks",
    "boston-celtics": "Boston_Celtics",
    "brooklyn-nets": "Brooklyn_Nets",
    "charlotte-hornets": "Charlotte_Hornets",
    "chicago-bulls": "Chicago_Bulls",
    "cleveland-cavaliers": "Cleveland_Cavaliers",
    "dallas-mavericks": "Dallas_Mavericks",
    "denver-nuggets": "Denver_Nuggets",
    "detroit-pistons": "Detroit_Pistons",
    "golden-state-warriors": "Golden_State_Warriors",
    "houston-rockets": "Houston_Rockets",
    "indiana-pacers": "Indiana_Pacers",
    "los-angeles-clippers": "Los_Angeles_Clippers",
    "los-angeles-lakers": "Los_Angeles_Lakers",
    "memphis-grizzlies": "Memphis_Grizzlies",
    "miami-heat": "Miami_Heat",
    "milwaukee-bucks": "Milwaukee_Bucks",
    "minnesota-timberwolves": "Minnesota_Timberwolves",
    "new-orleans-pelicans": "New_Orleans_Pelicans",
    "new-york-knicks": "New_York_Knicks",
    "oklahoma-city-thunder": "Oklahoma_City_Thunder",
    "orlando-magic": "Orlando_Magic",
    "philadelphia-76ers": "Philadelphia_76ers",
    "phoenix-suns": "Phoenix_Suns",
    "portland-trail-blazers": "Portland_Trail_Blazers",
    "sacramento-kings": "Sacramento_Kings",
    "san-antonio-spurs": "San_Antonio_Spurs",
    "toronto-raptors": "Toronto_Raptors",
    "utah-jazz": "Utah_Jazz",
    "washington-wizards": "Washington_Wizards",
    # NFL
    "arizona-cardinals": "Arizona_Cardinals",
    "atlanta-falcons": "Atlanta_Falcons",
    "baltimore-ravens": "Baltimore_Ravens",
    "buffalo-bills": "Buffalo_Bills",
    "carolina-panthers": "Carolina_Panthers",
    "chicago-bears": "Chicago_Bears",
    "cincinnati-bengals": "Cincinnati_Bengals",
    "cleveland-browns": "Cleveland_Browns",
    "dallas-cowboys": "Dallas_Cowboys",
    "denver-broncos": "Denver_Broncos",
    "detroit-lions": "Detroit_Lions",
    "green-bay-packers": "Green_Bay_Packers",
    "houston-texans": "Houston_Texans",
    "indianapolis-colts": "Indianapolis_Colts",
    "jacksonville-jaguars": "Jacksonville_Jaguars",
    "kansas-city-chiefs": "Kansas_City_Chiefs",
    "las-vegas-raiders": "Las_Vegas_Raiders",
    "los-angeles-chargers": "Los_Angeles_Chargers",
    "los-angeles-rams": "Los_Angeles_Rams",
    "miami-dolphins": "Miami_Dolphins",
    "minnesota-vikings": "Minnesota_Vikings",
    "new-england-patriots": "New_England_Patriots",
    "new-orleans-saints": "New_Orleans_Saints",
    "new-york-giants": "New_York_Giants",
    "new-york-jets": "New_York_Jets",
    "philadelphia-eagles": "Philadelphia_Eagles",
    "pittsburgh-steelers": "Pittsburgh_Steelers",
    "san-francisco-49ers": "San_Francisco_49ers",
    "seattle-seahawks": "Seattle_Seahawks",
    "tampa-bay-buccaneers": "Tampa_Bay_Buccaneers",
    "tennessee-titans": "Tennessee_Titans",
    "washington-commanders": "Washington_Commanders",
    # MLB
    "arizona-diamondbacks": "Arizona_Diamondbacks",
    "atlanta-braves": "Atlanta_Braves",
    "baltimore-orioles": "Baltimore_Orioles",
    "boston-red-sox": "Boston_Red_Sox",
    "chicago-cubs": "Chicago_Cubs",
    "chicago-white-sox": "Chicago_White_Sox",
    "cincinnati-reds": "Cincinnati_Reds",
    "cleveland-guardians": "Cleveland_Guardians",
    "colorado-rockies": "Colorado_Rockies",
    "detroit-tigers": "Detroit_Tigers",
    "houston-astros": "Houston_Astros",
    "kansas-city-royals": "Kansas_City_Royals",
    "los-angeles-angels": "Los_Angeles_Angels",
    "los-angeles-dodgers": "Los_Angeles_Dodgers",
    "miami-marlins": "Miami_Marlins",
    "milwaukee-brewers": "Milwaukee_Brewers",
    "minnesota-twins": "Minnesota_Twins",
    "new-york-mets": "New_York_Mets",
    "new-york-yankees": "New_York_Yankees",
    "oakland-athletics": "Oakland_Athletics",
    "philadelphia-phillies": "Philadelphia_Phillies",
    "pittsburgh-pirates": "Pittsburgh_Pirates",
    "san-diego-padres": "San_Diego_Padres",
    "san-francisco-giants": "San_Francisco_Giants",
    "seattle-mariners": "Seattle_Mariners",
    "st-louis-cardinals": "St._Louis_Cardinals",
    "tampa-bay-rays": "Tampa_Bay_Rays",
    "texas-rangers": "Texas_Rangers",
    "toronto-blue-jays": "Toronto_Blue_Jays",
    "washington-nationals": "Washington_Nationals",
}


def fetch_wikipedia_data(wiki_page_name: str) -> dict:
    """Fetch owner and sponsor data from a Wikipedia page."""
    result = {"owner": None, "sponsors": [], "error": None}
    url = f"https://en.wikipedia.org/wiki/{wiki_page_name}"
    headers = {"User-Agent": "Mozilla/5.0 (compatible; BehindTheJersey/0.1)"}
    
    try:
        req = Request(url, headers=headers)
        with urlopen(req, timeout=15) as resp:
            content = resp.read().decode("utf-8", errors="replace")
    except (URLError, HTTPError, TimeoutError) as e:
        result["error"] = str(e)
        return result
    
    # Extract owner from infobox
    for pattern in [
        r'Owner\(s\) = (.+?)(?:\n|\||\})',
        r'Owner = (.+?)(?:\n|\||\})',
        r'Owners?\s*=\s*(.+?)(?:\n|\|)',
    ]:
        match = re.search(pattern, content, re.IGNORECASE)
        if match:
            owner_text = match.group(1).strip()
            owner_text = re.sub(r'\[\[([^\]]+)\|([^\]]+)\]\]', r'\2', owner_text)
            owner_text = re.sub(r'\[\[([^\]]+)\]\]', r'\1', owner_text)
            owner_text = re.sub(r'<[^>]+>', '', owner_text).strip()
            owner_text = re.sub(r'\[\d+\]', '', owner_text).strip()
            if owner_text and owner_text.lower() not in ('none', 'tbd', '—', '–'):
                result["owner"] = owner_text
            break
    
    # Extract sponsors from infobox
    for pattern in [
        r'Kit manufacturer = (.+?)(?:\n|\||\})',
        r'Shirt sponsor = (.+?)(?:\n\|\||}\n)',
        r'Sponsor = (.+?)(?:\n|\||\})',
    ]:
        match = re.search(pattern, content, re.IGNORECASE)
        if match:
            sponsor_text = match.group(1).strip()
            sponsor_text = re.sub(r'\[\[([^\]]+)\|([^\]]+)\]\]', r'\2', sponsor_text)
            sponsor_text = re.sub(r'\[\[([^\]]+)\]\]', r'\1', sponsor_text)
            sponsor_text = re.sub(r'<[^>]+>', '', sponsor_text).strip()
            sponsor_text = re.sub(r'\[\d+\]', '', sponsor_text).strip()
            if sponsor_text and sponsor_text.lower() not in ('none', 'tbd', '—', '–'):
                result["sponsors"].append({
                    "name": sponsor_text,
                    "type": "company",
                    "category": "sponsor",
                    "rating": "D",
                    "rating_desc": "Unverified — needs review",
                    "flags": [],
                    "deal_value": None,
                    "sources": [url],
                    "verified": False,
                    "last_updated": datetime.now(timezone.utc).isoformat(),
                })
            break
    
    return result


def team_slug(name: str) -> str:
    """Convert team name to URL slug."""
    return name.lower().replace(" and ", "-").replace(" ", "-").replace(".", "")


def team_handle(name: str) -> str:
    """Convert team name to Twitter handle."""
    return "@" + name.lower().replace(" and ", "-").replace(" ", "")


def build_team_json(team_name: str, sport: str, league: str, country: str, wiki_data: dict | None = None) -> dict:
    """Build a team JSON object with contact/shame info + sponsor data."""
    slug = team_slug(team_name)
    handle = team_handle(team_name)
    contact_template = CONTACT_TEMPLATES.get(sport, CONTACT_TEMPLATES["soccer"])

    email = contact_template["email_pattern"].format(team=slug)
    twitter = contact_template["twitter_pattern"].format(team=handle.replace("@", ""))

    # Use Wikipedia sponsor data if available, otherwise empty
    sponsors = wiki_data.get("sponsors", []) if wiki_data else []
    owner = wiki_data.get("owner") if wiki_data else None

    return {
        "team": team_name,
        "sport": sport,
        "league": league,
        "country": country if country else "Unknown",
        "contact": {
            "phone": contact_template["phone_pattern"],
            "email": email,
            "twitter": f"@{twitter}",
            "website": f"https://www.{slug}.com"
        },
        "sponsors": sponsors,
        "owner": owner,
        "shame": {
            "description": f"Contact {team_name} to express discomfort about sponsor ratings",
            "methods": [
                {"type": "email", "address": contact_template["email_pattern"].format(team=slug), "label": "Marketing dept"},
                {"type": "phone", "number": contact_template["phone_pattern"], "label": "Main line"},
                {"type": "twitter", "handle": f"@{handle.replace('@', '')}", "label": "Tweet your concern"}
            ]
        },
        "last_updated": datetime.now(timezone.utc).strftime("%Y-%m-%d")
    }


def build_index_json(all_teams: dict) -> dict:
    """Build the master index JSON."""
    teams_list = []
    for key, data in all_teams.items():
        sport = data.get("sport", "")
        league = data.get("league", "")
        for team_name in data.get("teams", []):
            if isinstance(team_name, dict):
                team_name = team_name.get("name", "")
            teams_list.append({
                "name": team_name,
                "sport": sport,
                "league": league,
                "file": f"{team_slug(team_name)}.json"
            })

    return {
        "version": "0.1",
        "last_updated": datetime.now(timezone.utc).strftime("%Y-%m-%d"),
        "teams": teams_list,
        "total_teams": len(teams_list)
    }


def main():
    # Load collected data from raw_collected.json
    raw_file = OUTPUT_DIR / "raw_collected.json"
    if not raw_file.exists():
        print(f"ERROR: {raw_file} not found. Run collect_data.py first.", file=sys.stderr)
        sys.exit(1)

    with open(raw_file) as f:
        raw_data = json.load(f)

    all_teams = {}
    total_with_wiki = 0
    total_with_sponsors = 0

    # Build individual team JSON files
    for key, sport_data in raw_data.items():
        all_teams[key] = sport_data
        sport = sport_data.get("sport", "")
        league = sport_data.get("league", "")
        for team in sport_data.get("teams", []):
            team_name = team.get("name", "")
            slug = team_slug(team_name)
            
            # Fetch Wikipedia data for this team
            wiki_data = None
            wiki_page = TEAM_WIKIPEDIA.get(slug)
            if wiki_page:
                print(f"  Fetching Wikipedia for {team_name}...")
                wiki_data = fetch_wikipedia_data(wiki_page)
                if wiki_data.get("owner") or wiki_data.get("sponsors"):
                    total_with_wiki += 1
                if wiki_data.get("sponsors"):
                    total_with_sponsors += 1
                if wiki_data.get("error"):
                    print(f"    Wikipedia error: {wiki_data['error']}")
            
            team_json = build_team_json(team_name, sport, league, "", wiki_data)
            filename = f"{slug}.json"
            with open(DATA_DIR / filename, "w") as f:
                json.dump(team_json, f, indent=2)

    # Build master index
    index = build_index_json(all_teams)
    with open(DATA_DIR / "index.json", "w") as f:
        json.dump(index, f, indent=2)

    # Summary
    sports = set()
    for key, data in all_teams.items():
        sports.add(f"{data.get('sport', '')} ({data.get('league', '')})")
    print(f"\n=== Pipeline Output ===")
    print(f"Total teams: {index['total_teams']}")
    print(f"Sports: {', '.join(sorted(sports))}")
    print(f"Teams with Wikipedia data: {total_with_wiki}")
    print(f"Teams with sponsor data from Wikipedia: {total_with_sponsors}")
    print(f"Contact/shame methods: email, phone, Twitter")
    print(f"Output directory: data/")


if __name__ == "__main__":
    main()